### ISSUE TITLE
Window Bug Issue

### ISSUE THREAD

**Issue by Aran8276** [TheLoveableBananaNoodle/BubbleBoiBot#13]
Hello i was trying out the newest update of the bubbleboibot its was good but i'm having problem for the display. The window of the launcher window is off screen so i can't press the "Launch" button and when i moved the window to the top and hide the tittle part it does not work.

![image](https://user-images.githubusercontent.com/20200187/66373954-208d9900-e9d4-11e9-9021-eac14ac6f829.jpg)

**Comment by TheLoveableBananaNoodle** [comment]
Your issue has been recognized and should be fixed by BubbleBoiBot v1.8.1

**Comment by TheLoveableBananaNoodle** [comment]
v1.81 has released and your issue should be fixed. Issue closed.
EDIT: v1.82 has now changed the resolution to 950x700pixels. This should fix this issue for most displays.
