### ISSUE TITLE
Launcher text is spread out incorrectly and scroll bar doesn't work properly

### ISSUE THREAD

**Issue by Buddermario7** [TheLoveableBananaNoodle/BubbleBoiBot#14]
Rather than all options for a launcher setting being on the same line, each option has its own line. In addition, the scroll bar doesn't go all the way to the bottom.

![image](https://user-images.githubusercontent.com/29782686/66505711-e2f34380-ea99-11e9-845d-eef92a0c4c4f.png)

**Comment by TheLoveableBananaNoodle** [comment]
The scroll bar is not broken. The reason it does not go down is because your display size is smaller than what the launcher uses.

In a future update, I will make the launcher wider instead of heightened, this way more people can use the bot.

**Comment by TheLoveableBananaNoodle** [comment]
Version 1.82 has been released. The display resolution is now 950x700 pixels, so it should fit the vast majority of displays. Thank you for notifying me of the issue. Issue closed.
