### ISSUE TITLE
Task exception was never retrieved future:

### ISSUE THREAD

**Issue by Aran8276** [TheLoveableBananaNoodle/BubbleBoiBot#15]
Task exception was never retrieved
future: <Task finished coro=<AsyncClient._handle_eio_message() done, defined at C:\Users\ACER\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\asyncio_client.py:418> exception=KeyError('myID')>
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\asyncio_client.py", line 435, in _handle_eio_message
    await self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\asyncio_client.py", line 310, in _handle_event
    r = await self._trigger_event(data[0], namespace, *data[1:])
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python37\lib\site-packages\socketio\asyncio_client.py", line 361, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "C:\Users\ACER\Desktop\BubbleBoiBot-master\BubbleBoiBot v1.82\BubbleBoiBot.py", line 736, in on_lobbyPlayerDrawing
    if data == GAME_DATA["myID"]:
KeyError: 'myID'
Any fix?

**Comment by TheLoveableBananaNoodle** [comment]
When did this start happening and on what version? Did you change any code at all. What modules have you installed?

**Comment by Aran8276** [comment]
I never change any code it happens sometimes and not always 
It happens while finding player

**Comment by TheLoveableBananaNoodle** [comment]
Strange. I might remove player finding in v1.9 anyway due to it requiring a VPN and it be the only feature requiring a VPN to stop IP Targetting from Skribbl.io (limits connections)

**Comment by Aran8276** [comment]
Can you add a batch file to terminate all of the bot because it will a pain if i need to nonstop cmd spawning. Also how do you spawn different spam chat at once 
Example: BubblyBoiBot: Want a bot with auto spam, drawing, reconnection, user searching and link filter for easy link spam?

Or a bot with custom image drawing of an image inside a folder or random images inside a folder?

Or a bot with a simple GUI with every possible setting that will remember the settings you used?

Download the *NEW* BubbleBoiBot here: https://theloveablebanananoodle,github,io/

**Comment by TheLoveableBananaNoodle** [comment]
1. Idea has been noted.
2. That's something I add to advertise the bot. To do it I go into the actual bot's code and alter it. I will think about adding it in a future update as a feature.
