### ISSUE TITLE
Won't Launch

### ISSUE THREAD

**Issue by HuayraOCE** [TheLoveableBananaNoodle/BubbleBoiBot#19]
Hello, when I launch "launcher.bat" nothing happens. Any ideas why?

**Comment by TheLoveableBananaNoodle** [comment]
Hello HuayraOCE!

Firstly, make sure you've followed the tutorial on the main page fully and properly, including installing the correct version of python (32bit or 64bit) checking all the boxes told to check, etc. This should fix any issues. If the issues are not fixed, reply here.

**Comment by TheLoveableBananaNoodle** [comment]
closed due to lack of response; invalid.
