### ISSUE TITLE
"The screen cannot be set to the number of lines and columns specified."

### ISSUE THREAD

**Issue by ar06x** [TheLoveableBananaNoodle/BubbleBoiBot#20]
This error happens when running Launch.bat

![image](https://user-images.githubusercontent.com/45273698/71771148-ac945b80-2f04-11ea-93da-500d5d869e88.png)

**Comment by NightMean** [comment]
Same issue, the window just blinks and nothing opens. The error is the same on freshly installed windows machine with the recommended python.

**Comment by TheLoveableBananaNoodle** [comment]
Yeah, IDK why, I think it has something to do with perspective size...

Anyway, the bot no longer works now; skribbl.io must've finally fixed their bot issue lol
#RIPBUBBLEBOIBOT
2019-2020
